M48
; DRILL file {KiCad 9.0.6} date 2026-03-02T14:00:23-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-03-02T14:00:23-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X103.11Y-102.82
X108.89Y-102.82
T2
X76.1Y-75.4
X76.1Y-105.4
X135.1Y-75.4
X135.1Y-105.4
M30
